experiment_name: SAM Test
output_base_dir: runs
augmentation:
  input_images_dir: dat\unstacked\images
  input_labels_dir: dat\unstacked\labels
  output_dir: dat\training_data
  output_format: tif
  include_original: true
  n_augmentations: 4
  treat_3d_as_2d: false
  rotation_range: 90
  flip_horizontal: true
  flip_vertical: true
  gaussian_blur_prob: 0.3
  gaussian_noise_prob: 0.3
  brightness_contrast: true
training:
  images_dir: dat\training_data\images
  labels_dir: dat\training_data\labels
  model_type: vit_b_lm
  patch_shape:
  - 512
  - 512
  batch_size: 1
  n_epochs: 5
  learning_rate: 1.0e-05
  val_split: 0.1
  checkpoint_name: SAM Test
  resume_from_checkpoint: null
  export_path: null
log_level: INFO
