experiment_name: "full_sam_vit_h_a100"
output_base_dir: "runs"
augmentation: null
training:
  images_dir: "dat/augmented_training_data/images"
  labels_dir: "dat/augmented_training_data/labels"
  model_type: "vit_h"
  patch_shape: [512, 512]
  batch_size: 8
  n_epochs: 100
  n_samples: 1900
  n_objects_per_batch: 5
  num_workers: 16
  learning_rate: 5.0e-5
  val_split: 0.1
  shuffle_data: true
  shuffle_seed: 42
  train_instance_segmentation_only: false
  use_min_instance_sampler: true
  min_instances_per_patch: 1
  min_instance_size: 25
  sampler_max_tries: 10000
  checkpoint_name: "full_sam_vit_h_a100"
  resume_from_checkpoint: null
  export_path: "final_models/full_sam_vit_h_a100.pt"
