experiment_name: "quick_test_vit_b_a40_all"
output_base_dir: "runs"
augmentation: null
training:
  images_dir: "dat/augmented_training_data/images"
  labels_dir: "dat/augmented_training_data/labels"
  model_type: "vit_b_lm"
  patch_shape: [512, 512]
  batch_size: 4
  n_epochs: 3
  n_samples: 5000
  num_workers: 8
  learning_rate: 1.0e-5
  val_split: 0.05
  shuffle_data: true
  shuffle_seed: 42
  train_instance_segmentation_only: false
  use_min_instance_sampler: true
  min_instances_per_patch: 1
  min_instance_size: 1  # Minimum 1 pixel to avoid empty objects but keep all real instances
  checkpoint_name: "quick_test_vit_b_a40_all"
  resume_from_checkpoint: null